// Minimum lengths
const USERNAME_LENGTH = 6
const PASSWORD_LENGTH = 8
const NICKNAME_LENGTH = 6
const EVENTNAME_LENGTH = 10
const DESCRIPTION_LENGTH = 10
const RECURRENCENAME_LENGTH = 10
const VENUENAME_LENGTH = 4
const SHOWNAME_LENGTH = 2
